openapi: 3.0.1
info:
  title: MAHFileProcess_API
  description: API Definition of MAHFileProcess_API
  version: 1.0.0
servers:
- url: http://localhost:8290/mahFileProcessAPI
paths:
  /:
    post:
      responses:
        default:
          description: Default response
