openapi: 3.0.1
info:
  title: DataMapMandatory
  description: API Definition of DataMapTest
  version: 1.0.0
servers:
- url: http://localhost:8290/dataMapMandatory
paths:
  /:
    get:
      responses:
        default:
          description: Default response
