openapi: 3.0.1
info:
  title: MemberRemove_API
  description: API Definition of MemberRemove_API
  version: 1.0.0
servers:
- url: http://localhost:8290/memberRemove
paths:
  /:
    post:
      responses:
        default:
          description: Default response
