openapi: 3.0.1
info:
  title: OutLookMail
  description: API Definition of OutLookMail
  version: 1.0.0
servers:
- url: http://localhost:8290/outLookMail
paths:
  /:
    get:
      responses:
        default:
          description: Default response
