openapi: 3.0.1
info:
  title: CallMultiple_API
  description: API Definition of CallMultiple_API
  version: 1.0.0
servers:
- url: http://localhost:8290/callMultipleAPI
paths:
  /:
    get:
      responses:
        default:
          description: Default response
