openapi: 3.0.1
info:
  title: DynamicQueryCall_API
  description: API Definition of DynamicQueryCall_API
  version: 1.0.0
servers:
- url: http://localhost:8290/DynamicQueryCall
paths:
  /:
    post:
      responses:
        default:
          description: Default response
