openapi: 3.0.1
info:
  title: GlobalProperties_API
  description: API Definition of GlobalProperties_API
  version: 1.0.0
servers:
- url: http://localhost:8290/globalProperties
paths:
  /:
    get:
      responses:
        default:
          description: Default response
