openapi: 3.0.1
info:
  title: TestProps
  description: API Definition of TestProps
  version: 1.0.0
servers:
- url: http://localhost:8290/testProperties
paths:
  /:
    get:
      responses:
        default:
          description: Default response
