openapi: 3.0.1
info:
  title: MailConnector
  description: API Definition of MailConnector
  version: 1.0.0
servers:
- url: http://localhost:8290/mailConnector
paths:
  /:
    post:
      responses:
        default:
          description: Default response
