openapi: 3.0.1
info:
  title: ReadCustomer
  description: API Definition of ReadCustomer
  version: 1.0.0
servers:
- url: http://localhost:8290/readCustomer
paths:
  /:
    get:
      responses:
        default:
          description: Default response
