openapi: 3.0.1
info:
  title: Clone_Mediator_Test
  description: API Definition of Clone_Mediator_Test
  version: 1.0.0
servers:
- url: http://localhost:8290/clone
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
