openapi: 3.0.1
info:
  title: DynamicSeq_API
  description: API Definition of DynamicSeq_API
  version: 1.0.0
servers:
- url: http://localhost:8290/dynamicSeq_API
paths:
  /:
    get:
      responses:
        default:
          description: Default response
