openapi: 3.0.1
info:
  title: Customer
  description: API Definition of Customer
  version: 1.0.0
servers:
- url: http://localhost:8290/serverRoot/tmf-api/customerManagement/v4/customer
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
  /{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
