openapi: 3.0.1
info:
  title: MemberRemove2
  description: API Definition of MemberRemove2
  version: 1.0.0
servers:
- url: http://localhost:8290/memberRemove2
paths:
  /:
    post:
      responses:
        default:
          description: Default response
