openapi: 3.0.1
info:
  title: Contract_Creation
  description: API Definition of Contract_Creation
  version: 1.0.0
servers:
- url: http://localhost:8290/create-contract
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
