openapi: 3.0.1
info:
  title: createCustomerSeqApi
  description: API Definition of createCustomerSeqApi
  version: 1.0.0
servers:
- url: http://localhost:8290/uol/composite/createCustomerDetails
paths:
  /:
    post:
      responses:
        default:
          description: Default response
