openapi: 3.0.1
info:
  title: EligibilityConfigCheck_API
  description: API Definition of EligibilityConfigCheck_API
  version: 1.0.0
servers:
- url: http://localhost:8290/check-eligibility
paths:
  /:
    post:
      responses:
        default:
          description: Default response
