openapi: 3.0.1
info:
  title: DynQuery_API
  description: API Definition of DynQuery_API
  version: 1.0.0
servers:
- url: http://localhost:8290/dynQueryAPI
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
