openapi: 3.0.1
info:
  title: PrabhasUngulam
  description: API Definition of PrabhasUngulam
  version: 1.0.0
servers:
- url: http://localhost:8290/prabhasUngulam
paths:
  /:
    get:
      responses:
        default:
          description: Default response
