openapi: 3.0.1
info:
  title: Cache_Testing_API
  description: API Definition of Cache_Testing_API
  version: 1.0.0
servers:
- url: http://localhost:8290/cache_Testing_API
paths:
  /:
    get:
      responses:
        default:
          description: Default response
