openapi: 3.0.1
info:
  title: MessageProcessorRMQ
  description: API Definition of MessageProcessorRMQ
  version: 1.0.0
servers:
- url: http://localhost:8290/messageProcessorRMQ
paths:
  /:
    post:
      responses:
        default:
          description: Default response
