openapi: 3.0.1
info:
  title: Customer_LE_Test
  description: API Definition of Customer_LE_Test
  version: 1.0.0
servers:
- url: http://localhost:8290/customer_localEntryTest
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
