openapi: 3.0.1
info:
  title: XSLTAPI
  description: API Definition of XSLTAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/xslt
paths:
  /:
    post:
      responses:
        default:
          description: Default response
