openapi: 3.0.1
info:
  title: Advance_API
  description: API Definition of Advance_API
  version: 1.0.0
servers:
- url: http://localhost:8290/advance
paths:
  /:
    get:
      responses:
        default:
          description: Default response
