openapi: 3.0.1
info:
  title: Barring_API
  description: API Definition of Barring_API
  version: 1.0.0
servers:
- url: http://localhost:8290/barring
paths:
  /:
    get:
      responses:
        default:
          description: Default response
