openapi: 3.0.1
info:
  title: KYC_Calling_API
  description: API Definition of KYC_Calling_API
  version: 1.0.0
servers:
- url: http://localhost:8290/kyccalling
paths:
  /:
    get:
      responses:
        default:
          description: Default response
