openapi: 3.0.1
info:
  title: MSISDN_Validation_API
  description: API Definition of MSISDN_Validation_API
  version: 1.0.0
servers:
- url: http://localhost:8290/msisdnvalidation
paths:
  /:
    get:
      responses:
        default:
          description: Default response
