openapi: 3.0.1
info:
  title: OutStanding_API
  description: API Definition of OutStanding_API
  version: 1.0.0
servers:
- url: http://localhost:8290/outstandingEligibilityCheck
paths:
  /:
    get:
      responses:
        default:
          description: Default response
