openapi: 3.0.1
info:
  title: Pending_Request_API
  description: API Definition of Pending_Request_API
  version: 1.0.0
servers:
- url: http://localhost:8290/pendingrequest
paths:
  /:
    get:
      responses:
        default:
          description: Default response
